---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: flask8
    labels:
      app: flask8-app
    namespace: default
  spec:
    replicas: 1
    selector: 
      matchLabels:
        app: flask8-app
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: flask8-app
      spec:
        containers:
        - image: monkbilal/flaskapp:latest
          imagePullPolicy: Always
          name: flask8-app
          ports:
          - containerPort: 4000
            protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 20  
          livenessProbe:
            tcpSocket:
              port: 4000    
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            limits:
              cpu: "0.5"
              memory: 200Mi
            requests:
              cpu: "0.2"
              memory: "150"

---
  apiVersion: v1
  kind: Service
  metadata:
    name: flask8-app-service
  spec:
    selector:
      app: flask8-app
    type: NodePort
    ports:
      -  protocol: TCP
         targetPort: 4000
         port: 4000
         nodePort: 30002
